apiVersion: mulitcluster.practice.com/v1alpha1
kind: MultiClusterResource
metadata:
  name: mypod.pod
  namespace: default
spec:
   template:
     apiVersion: v1
     kind: Pod
     metadata:
       name: multicluster-pod
       namespace: default
     spec:
       containers:
         - image: busybox
           command:
             - sleep
             - "3600"
           imagePullPolicy: IfNotPresent
           name: busybox
       restartPolicy: Always
   placement:
     clusters:
#       - name: cluster1
       - name: cluster2
       - name: cluster3
   # 可以不填写
   customize:
     clusters:
       - name: cluster1
         action:
           - path: "/spec/containers/0/image"
             op: "replace"
             value:
               - "nginx:1.19.0-alpine"
       - name: cluster2
         action:
           - path: "/metadata/annotations/example"
             value:
               - "example"
             op: "add"
           - path: "/spec/containers/0/image"
             value:
               - "nginx:1.19.0-alpine"
             op: "replace"
       - name: cluster3
         action:
           - path: "/spec/containers/0/image"
             op: "replace"
             value:
               - "nginx:1.17.0-alpine"

           # pod patch 操作默认不能新增容器，所以如下操作不行
           #           - path: "/spec/containers/-"
           #             value:
           #               - "name=busybox11"
           #               - "image=nginx:1.19.0-alpine"
           #             op: "add"

    